<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('tb_formpeny', function (Blueprint $table) {
            $table->integer('id_peny')->autoIncrement();
            $table->date('tgl_kom')->nullable(false);
            $table->string('nama_peny', 100)->nullable(false);
            $table->integer('id_gi')->nullable(false);
            $table->integer('id_rtugi')->nullable(false);
            $table->string('rtu_addrs', 50)->nullable(false);
            $table->integer('id_medkom')->nullable(false);
            $table->string('s_cb', 100)->nullable(true);
            $table->string('s_lr', 100)->nullable(true);
            $table->string('s_ocr', 100)->nullable(true);
            $table->string('s_ocri', 100)->nullable(true);
            $table->string('s_dgr', 100)->nullable(true);
            $table->string('s_cbtr', 100)->nullable(true);
            $table->string('s_ar', 100)->nullable(true);
            $table->string('s_aru', 100)->nullable(true);
            $table->string('s_tc', 150)->nullable(true);
            $table->string('c_cb', 150)->nullable(true);
            $table->string('c_aru', 150)->nullable(true);
            $table->string('c_rst', 150)->nullable(true);
            $table->string('c_tc', 100)->nullable(true);
            $table->string('ir_rtu', 10)->nullable(true);
            $table->string('is_rtu', 10)->nullable(true);
            $table->string('it_rtu', 10)->nullable(true);
            $table->string('ir_ms', 10)->nullable(true);
            $table->string('is_ms', 10)->nullable(true);
            $table->string('it_ms', 10)->nullable(true);
            $table->string('ir_scale', 10)->nullable(true);
            $table->string('is_scale', 10)->nullable(true);
            $table->string('it_scale', 10)->nullable(true);
            $table->string('fir_rtu', 50)->nullable(true);
            $table->string('fis_rtu', 50)->nullable(true);
            $table->string('fit_rtu', 50)->nullable(true);
            $table->string('fin_rtu', 50)->nullable(true);
            $table->string('fir_ms', 50)->nullable(true);
            $table->string('fis_ms', 50)->nullable(true);
            $table->string('fit_ms', 50)->nullable(true);
            $table->string('fin_ms', 50)->nullable(true);
            $table->string('fir_scale', 50)->nullable(true);
            $table->string('fis_scale', 50)->nullable(true);
            $table->string('fit_scale', 50)->nullable(true);
            $table->string('fin_scale', 50)->nullable(true);
            $table->string('p_rtu', 50)->nullable(true);
            $table->string('p_ms', 50)->nullable(true);
            $table->string('p_scale', 50)->nullable(true);
            $table->string('v_rtu', 50)->nullable(true);
            $table->string('v_ms', 50)->nullable(true);
            $table->string('v_scale', 50)->nullable(true);
            $table->string('f_rtu', 50)->nullable(true);
            $table->string('f_ms', 50)->nullable(true);
            $table->string('f_scale', 50)->nullable(true);
            $table->integer('id_komkp')->nullable(false);
            $table->string('nama_user', 10)->nullable(false);
            $table->string('id_pelms', 50)->nullable(false);
            $table->string('pelrtu', 100)->nullable(false);
            $table->string('ketpeny', 1000)->nullable(false);
            $table->timestamp('lastupdate', 6)->nullable(false)->default(DB::raw('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'));
            $table->charset = 'latin1';
            $table->collation = 'latin1_swedish_ci';
            $table->engine = 'InnoDB';
        });
        // Insert data
        DB::table('tb_formpeny')->insert([
            ['id_peny' => 55, 'tgl_kom' => '2020-06-22', 'nama_peny' => 'PULOREJO', 'id_gi' => 64, 'id_rtugi' => 5, 'rtu_addrs' => '', 'id_medkom' => 3, 's_cb' => 'open_1,open_3,open_4,close_1,close_3,close_4', 's_lr' => 'local_1,local_3,local_4,remote_1,remote_3,remote_4', 's_ocr' => 'ocrd_1,ocrd_3,ocrd_4,ocra_1,ocra_3,ocra_4', 's_ocri' => 'ocrid_1,ocrid_3,ocrid_4,ocria_1,ocria_3,ocria_4', 's_dgr' => '', 's_cbtr' => 'scbtrd_1,scbtrd_3,scbtrd_4,scbtra_1,scbtra_3,scbtra_4', 's_ar' => '', 's_aru' => '', 's_tc' => '', 'c_cb' => 'cbctrl_op_1,cbctrl_op_3,cbctrl_op_4,cbctrl_cl_1,cbctrl_cl_3,cbctrl_cl_4', 'c_aru' => '', 'c_rst' => 'rrctrl_on_1,rrctrl_on_3,rrctrl_on_4', 'c_tc' => '', 'ir_rtu' => '0', 'is_rtu' => '0', 'it_rtu' => '0', 'ir_ms' => '0', 'is_ms' => '0', 'it_ms' => '0', 'ir_scale' => '1', 'is_scale' => '1', 'it_scale' => '1', 'fir_rtu' => '440', 'fis_rtu' => '440', 'fit_rtu' => '440', 'fin_rtu' => '', 'fir_ms' => '440', 'fis_ms' => '440', 'fit_ms' => '440', 'fin_ms' => '440', 'fir_scale' => '0,5', 'fis_scale' => '', 'fit_scale' => '', 'fin_scale' => '', 'p_rtu' => '', 'p_ms' => '', 'p_scale' => '', 'v_rtu' => '', 'v_ms' => '', 'v_scale' => '', 'f_rtu' => '', 'f_ms' => '', 'f_scale' => '', 'id_komkp' => 2, 'nama_user' => '', 'id_pelms' => '1', 'pelrtu' => 'BAYU/FAISAL/LORA', 'ketpeny' => 'Control CB REAL', 'lastupdate' => '2020-06-22 09:08:42.000000'],
            ['id_peny' => 56, 'tgl_kom' => '2020-07-14', 'nama_peny' => 'JETAK', 'id_gi' => 87, 'id_rtugi' => 5, 'rtu_addrs' => '192.168.39', 'id_medkom' => 3, 's_cb' => 'open_1,open_3,open_4,close_1,close_3,close_4', 's_lr' => 'local_1,local_3,local_4,remote_1,remote_3,remote_4', 's_ocr' => 'ocrd_1,ocrd_3,ocrd_4,ocra_1,ocra_3,ocra_4', 's_ocri' => 'ocrid_1,ocrid_3,ocrid_4,ocria_1,ocria_3,ocria_4', 's_dgr' => 'dgrd_1,dgrd_3,dgrd_4,dgra_1,dgra_3,dgra_4', 's_cbtr' => 'scbtrd_1,scbtrd_3,scbtrd_4,scbtra_1,scbtra_3,scbtra_4', 's_ar' => '', 's_aru' => '', 's_tc' => '', 'c_cb' => 'cbctrl_op_1,cbctrl_op_3,cbctrl_op_4,cbctrl_cl_1,cbctrl_cl_3,cbctrl_cl_4', 'c_aru' => '', 'c_rst' => 'rrctrl_on_1,rrctrl_on_3', 'c_tc' => '', 'ir_rtu' => '', 'is_rtu' => '', 'it_rtu' => '', 'ir_ms' => '', 'is_ms' => '', 'it_ms' => '', 'ir_scale' => '', 'is_scale' => '', 'it_scale' => '', 'fir_rtu' => '4.8', 'fis_rtu' => '', 'fit_rtu' => '', 'fin_rtu' => '10', 'fir_ms' => '4.8', 'fis_ms' => '', 'fit_ms' => '', 'fin_ms' => '4.8', 'fir_scale' => '0.5', 'fis_scale' => '', 'fit_scale' => '', 'fin_scale' => '0.0065', 'p_rtu' => '', 'p_ms' => '', 'p_scale' => '', 'v_rtu' => '', 'v_ms' => '', 'v_scale' => '', 'f_rtu' => '', 'f_ms' => '', 'f_scale' => '', 'id_komkp' => 2, 'nama_user' => '', 'id_pelms' => '4', 'pelrtu' => 'RAHMAD/TAUFIK', 'ketpeny' => '', 'lastupdate' => '2020-07-14 09:04:43.000000'],
            ['id_peny' => 57, 'tgl_kom' => '2020-07-14', 'nama_peny' => 'TANJUNG ARUM', 'id_gi' => 87, 'id_rtugi' => 5, 'rtu_addrs' => '', 'id_medkom' => 3, 's_cb' => 'open_1,open_3,open_4,close_1,close_3,close_4', 's_lr' => 'local_1,local_3,local_4,remote_1,remote_3,remote_4', 's_ocr' => 'ocrd_1,ocrd_3,ocrd_4,ocra_1,ocra_3,ocra_4', 's_ocri' => 'ocrid_1,ocrid_3,ocrid_4,ocria_1,ocria_3,ocria_4', 's_dgr' => 'dgrd_1,dgrd_3,dgrd_4,dgra_1,dgra_3,dgra_4', 's_cbtr' => 'scbtrd_1,scbtrd_3,scbtrd_4,scbtra_1,scbtra_3,scbtra_4', 's_ar' => '', 's_aru' => '', 's_tc' => '', 'c_cb' => 'cbctrl_op_1,cbctrl_op_3,cbctrl_op_4,cbctrl_cl_1,cbctrl_cl_3,cbctrl_cl_4', 'c_aru' => '', 'c_rst' => 'rrctrl_on_1,rrctrl_on_3', 'c_tc' => '', 'ir_rtu' => '', 'is_rtu' => '', 'it_rtu' => '', 'ir_ms' => '', 'is_ms' => '', 'it_ms' => '', 'ir_scale' => '', 'is_scale' => '', 'it_scale' => '', 'fir_rtu' => '4.9', 'fis_rtu' => '', 'fit_rtu' => '', 'fin_rtu' => '10', 'fir_ms' => '4.9', 'fis_ms' => '', 'fit_ms' => '', 'fin_ms' => '10', 'fir_scale' => '0.5', 'fis_scale' => '', 'fit_scale' => '', 'fin_scale' => '0.0065', 'p_rtu' => '', 'p_ms' => '', 'p_scale' => '', 'v_rtu' => '', 'v_ms' => '', 'v_scale' => '', 'f_rtu' => '', 'f_ms' => '', 'f_scale' => '', 'id_komkp' => 2, 'nama_user' => '', 'id_pelms' => '4', 'pelrtu' => 'RAHMAD/TAUFIK', 'ketpeny' => '', 'lastupdate' => '2020-07-14 09:06:03.000000'],
            ['id_peny' => 58, 'tgl_kom' => '2020-07-14', 'nama_peny' => 'EASTERNTEX', 'id_gi' => 87, 'id_rtugi' => 5, 'rtu_addrs' => '192.168.39', 'id_medkom' => 3, 's_cb' => 'open_1,open_3,open_4,close_1,close_3,close_4', 's_lr' => 'local_1,local_3,local_4,remote_1,remote_3,remote_4', 's_ocr' => 'ocrd_1,ocrd_3,ocrd_4,ocra_1,ocra_3,ocra_4', 's_ocri' => 'ocrid_1,ocrid_3,ocrid_4,ocria_1,ocria_3,ocria_4', 's_dgr' => 'dgrd_1,dgrd_3,dgrd_4,dgra_1,dgra_3,dgra_4', 's_cbtr' => 'scbtrd_1,scbtrd_3,scbtrd_4,scbtra_1,scbtra_3,scbtra_4', 's_ar' => '', 's_aru' => '', 's_tc' => '', 'c_cb' => 'cbctrl_op_1,cbctrl_op_3,cbctrl_op_4,cbctrl_cl_1,cbctrl_cl_3,cbctrl_cl_4', 'c_aru' => '', 'c_rst' => 'rrctrl_on_1,rrctrl_on_3', 'c_tc' => '', 'ir_rtu' => '', 'is_rtu' => '', 'it_rtu' => '', 'ir_ms' => '', 'is_ms' => '', 'it_ms' => '', 'ir_scale' => '', 'is_scale' => '', 'it_scale' => '', 'fir_rtu' => '4.1', 'fis_rtu' => '', 'fit_rtu' => '', 'fin_rtu' => '10', 'fir_ms' => '4.1', 'fis_ms' => '', 'fit_ms' => '', 'fin_ms' => '10', 'fir_scale' => '0.5', 'fis_scale' => '0.5', 'fit_scale' => '', 'fin_scale' => '0.0065', 'p_rtu' => '', 'p_ms' => '', 'p_scale' => '', 'v_rtu' => '', 'v_ms' => '', 'v_scale' => '', 'f_rtu' => '', 'f_ms' => '', 'f_scale' => '', 'id_komkp' => 2, 'nama_user' => '', 'id_pelms' => '4', 'pelrtu' => 'RAHMAD/TAUFIK', 'ketpeny' => '', 'lastupdate' => '2020-07-14 09:03:25.000000'],
            ['id_peny' => 59, 'tgl_kom' => '2020-07-14', 'nama_peny' => 'SAMPOERNA 2', 'id_gi' => 87, 'id_rtugi' => 5, 'rtu_addrs' => '', 'id_medkom' => 3, 's_cb' => 'open_1,open_3,open_4,close_1,close_3,close_4', 's_lr' => 'local_1,local_3,local_4,remote_1,remote_3,remote_4', 's_ocr' => '', 's_ocri' => 'ocrid_1,ocrid_3,ocrid_4,ocria_1,ocria_3,ocria_4', 's_dgr' => 'dgrd_1,dgrd_3,dgrd_4,dgra_1,dgra_3,dgra_4', 's_cbtr' => 'scbtrd_1,scbtrd_3,scbtrd_4,scbtra_1,scbtra_3,scbtra_4', 's_ar' => '', 's_aru' => '', 's_tc' => '', 'c_cb' => 'cbctrl_op_1,cbctrl_op_3,cbctrl_op_4,cbctrl_cl_1,cbctrl_cl_3,cbctrl_cl_4', 'c_aru' => '', 'c_rst' => 'rrctrl_on_1,rrctrl_on_3', 'c_tc' => '', 'ir_rtu' => '', 'is_rtu' => '', 'it_rtu' => '', 'ir_ms' => '', 'is_ms' => '', 'it_ms' => '', 'ir_scale' => '', 'is_scale' => '', 'it_scale' => '', 'fir_rtu' => '4.1', 'fis_rtu' => '', 'fit_rtu' => '', 'fin_rtu' => '10', 'fir_ms' => '4.1', 'fis_ms' => '', 'fit_ms' => '', 'fin_ms' => '10', 'fir_scale' => '0.5', 'fis_scale' => '', 'fit_scale' => '', 'fin_scale' => '0.0065', 'p_rtu' => '', 'p_ms' => '', 'p_scale' => '', 'v_rtu' => '', 'v_ms' => '', 'v_scale' => '', 'f_rtu' => '', 'f_ms' => '', 'f_scale' => '', 'id_komkp' => 2, 'nama_user' => '', 'id_pelms' => '4', 'pelrtu' => 'RAHMAD/TAUFIK', 'ketpeny' => 'Tidak diuji indikasi OCR', 'lastupdate' => '2020-07-14 09:09:03.000000'],
            ['id_peny' => 60, 'tgl_kom' => '2020-08-11', 'nama_peny' => 'Manyar', 'id_gi' => 36, 'id_rtugi' => 4, 'rtu_addrs' => 'dnp 3.0', 'id_medkom' => 3, 's_cb' => 'open_1,close_1', 's_lr' => 'local_1,remote_1', 's_ocr' => 'ocrd_1,ocra_1', 's_ocri' => '', 's_dgr' => 'dgrd_1,dgra_1', 's_cbtr' => '', 's_ar' => '', 's_aru' => '', 's_tc' => '', 'c_cb' => 'cbctrl_op_1,cbctrl_cl_1', 'c_aru' => '', 'c_rst' => 'rrctrl_on_1', 'c_tc' => '', 'ir_rtu' => '', 'is_rtu' => '', 'it_rtu' => '', 'ir_ms' => '', 'is_ms' => '', 'it_ms' => '', 'ir_scale' => '', 'is_scale' => '', 'it_scale' => '', 'fir_rtu' => '1,2 kA', 'fis_rtu' => '', 'fit_rtu' => '1,2 kA', 'fin_rtu' => '10', 'fir_ms' => '1198 A', 'fis_ms' => '', 'fit_ms' => '1200 A', 'fin_ms' => '10', 'fir_scale' => '1', 'fis_scale' => '1\'1', 'fit_scale' => '', 'fin_scale' => '1', 'p_rtu' => '', 'p_ms' => '', 'p_scale' => '', 'v_rtu' => '', 'v_ms' => '', 'v_scale' => '', 'f_rtu' => '', 'f_ms' => '', 'f_scale' => '', 'id_komkp' => 2, 'nama_user' => '', 'id_pelms' => '2', 'pelrtu' => 'SELAMET & TEDDY', 'ketpeny' => 'HAR RUTIN\r\nUNTUK ARUS GANGGUAN NETRAL MUNCUL D HMI', 'lastupdate' => '2020-08-11 07:51:10.000000'],
            ['id_peny' => 61, 'tgl_kom' => '2020-08-11', 'nama_peny' => 'ARUKI', 'id_gi' => 36, 'id_rtugi' => 4, 'rtu_addrs' => 'DNP 3.0', 'id_medkom' => 3, 's_cb' => 'open_1,close_1', 's_lr' => 'local_1,remote_1', 's_ocr' => 'ocrd_1,ocra_1', 's_ocri' => '', 's_dgr' => '', 's_cbtr' => 'scbtrd_1,scbtra_1', 's_ar' => '', 's_aru' => '', 's_tc' => '', 'c_cb' => 'cbctrl_op_1,cbctrl_cl_1', 'c_aru' => '', 'c_rst' => 'rrctrl_on_1', 'c_tc' => '', 'ir_rtu' => '', 'is_rtu' => '', 'it_rtu' => '', 'ir_ms' => '', 'is_ms' => '', 'it_ms' => '', 'ir_scale' => '', 'is_scale' => '', 'it_scale' => '', 'fir_rtu' => '1,2 kA', 'fis_rtu' => '', 'fit_rtu' => '1,2 kA', 'fin_rtu' => '8', 'fir_ms' => '1198 A', 'fis_ms' => '', 'fit_ms' => '1194 A', 'fin_ms' => '8', 'fir_scale' => '1', 'fis_scale' => '1\'', 'fit_scale' => '', 'fin_scale' => '', 'p_rtu' => '', 'p_ms' => '', 'p_scale' => '', 'v_rtu' => '', 'v_ms' => '', 'v_scale' => '', 'f_rtu' => '', 'f_ms' => '', 'f_scale' => '', 'id_komkp' => 2, 'nama_user' => '', 'id_pelms' => '2', 'pelrtu' => 'SELAMET & TEDDY', 'ketpeny' => 'ARUS DGR DIBUAT MUNCUL TIAP FASA DI HMI', 'lastupdate' => '2020-08-11 08:16:06.889019'],
            ['id_peny' => 62, 'tgl_kom' => '2020-08-11', 'nama_peny' => 'NGINDEN', 'id_gi' => 36, 'id_rtugi' => 4, 'rtu_addrs' => 'DNP 3.0', 'id_medkom' => 3, 's_cb' => 'open_1,close_1', 's_lr' => 'local_1,remote_1', 's_ocr' => 'ocrd_1,ocra_1', 's_ocri' => '', 's_dgr' => 'dgrd_1,dgra_1', 's_cbtr' => 'scbtrd_1,scbtra_1', 's_ar' => '', 's_aru' => '', 's_tc' => '', 'c_cb' => 'cbctrl_op_1,cbctrl_cl_1', 'c_aru' => '', 'c_rst' => 'rrctrl_on_1', 'c_tc' => '', 'ir_rtu' => '', 'is_rtu' => '', 'it_rtu' => '', 'ir_ms' => '', 'is_ms' => '', 'it_ms' => '', 'ir_scale' => '', 'is_scale' => '', 'it_scale' => '', 'fir_rtu' => '440', 'fis_rtu' => '', 'fit_rtu' => '452', 'fin_rtu' => '8', 'fir_ms' => '440', 'fis_ms' => '', 'fit_ms' => '452', 'fin_ms' => '9', 'fir_scale' => '1', 'fis_scale' => '1\'1', 'fit_scale' => '', 'fin_scale' => '1', 'p_rtu' => '', 'p_ms' => '', 'p_scale' => '', 'v_rtu' => '', 'v_ms' => '', 'v_scale' => '', 'f_rtu' => '', 'f_ms' => '', 'f_scale' => '', 'id_komkp' => 2, 'nama_user' => '', 'id_pelms' => '2', 'pelrtu' => 'SELAMET & TEDDY', 'ketpeny' => 'ARUS GANGGUAN DGR DIBUAT MUNCUL TIAP FASA DI HMI', 'lastupdate' => '2020-08-11 07:54:38.000000'],
            ['id_peny' => 63, 'tgl_kom' => '2020-08-11', 'nama_peny' => 'KRUKAH', 'id_gi' => 36, 'id_rtugi' => 4, 'rtu_addrs' => 'DNP', 'id_medkom' => 3, 's_cb' => 'open_1,close_1', 's_lr' => 'local_1,remote_1', 's_ocr' => 'ocrd_1,ocra_1', 's_ocri' => '', 's_dgr' => 'dgrd_1,dgra_1', 's_cbtr' => '', 's_ar' => '', 's_aru' => '', 's_tc' => '', 'c_cb' => 'cbctrl_op_1,cbctrl_cl_1', 'c_aru' => '', 'c_rst' => 'rrctrl_on_1', 'c_tc' => '', 'ir_rtu' => '', 'is_rtu' => '', 'it_rtu' => '', 'ir_ms' => '', 'is_ms' => '', 'it_ms' => '', 'ir_scale' => '', 'is_scale' => '', 'it_scale' => '', 'fir_rtu' => '599', 'fis_rtu' => '', 'fit_rtu' => '599', 'fin_rtu' => '8', 'fir_ms' => '599', 'fis_ms' => '', 'fit_ms' => '599', 'fin_ms' => '8', 'fir_scale' => '1', 'fis_scale' => '1\'', 'fit_scale' => '', 'fin_scale' => '1', 'p_rtu' => '', 'p_ms' => '', 'p_scale' => '', 'v_rtu' => '', 'v_ms' => '', 'v_scale' => '', 'f_rtu' => '', 'f_ms' => '', 'f_scale' => '', 'id_komkp' => 2, 'nama_user' => '', 'id_pelms' => '2', 'pelrtu' => 'SELAMET & TEDDY', 'ketpeny' => '', 'lastupdate' => '2020-08-11 08:16:10.404607'],
            ['id_peny' => 64, 'tgl_kom' => '2020-08-11', 'nama_peny' => 'KALIWARON', 'id_gi' => 36, 'id_rtugi' => 4, 'rtu_addrs' => 'DNP', 'id_medkom' => 3, 's_cb' => 'open_1,close_1', 's_lr' => 'local_1,remote_1', 's_ocr' => 'ocrd_1,ocra_1', 's_ocri' => '', 's_dgr' => 'dgrd_1,dgra_1', 's_cbtr' => '', 's_ar' => '', 's_aru' => '', 's_tc' => '', 'c_cb' => '', 'c_aru' => '', 'c_rst' => '', 'c_tc' => '', 'ir_rtu' => '', 'is_rtu' => '', 'it_rtu' => '', 'ir_ms' => '', 'is_ms' => '', 'it_ms' => '', 'ir_scale' => '', 'is_scale' => '', 'it_scale' => '', 'fir_rtu' => '1,2 kA', 'fis_rtu' => '600', 'fit_rtu' => '1,2 kA', 'fin_rtu' => '8', 'fir_ms' => '1200 a', 'fis_ms' => '600', 'fit_ms' => '1201 A', 'fin_ms' => '8', 'fir_scale' => '', 'fis_scale' => '\'', 'fit_scale' => '', 'fin_scale' => '1', 'p_rtu' => '', 'p_ms' => '', 'p_scale' => '', 'v_rtu' => '', 'v_ms' => '', 'v_scale' => '', 'f_rtu' => '', 'f_ms' => '', 'f_scale' => '', 'id_komkp' => 2, 'nama_user' => '', 'id_pelms' => '2', 'pelrtu' => 'SELAMET & TEDDY', 'ketpeny' => '', 'lastupdate' => '2020-08-11 08:15:40.153786'],
            ['id_peny' => 65, 'tgl_kom' => '2020-08-11', 'nama_peny' => 'ERLANGGA', 'id_gi' => 36, 'id_rtugi' => 4, 'rtu_addrs' => 'DNP', 'id_medkom' => 3, 's_cb' => 'open_1,close_1', 's_lr' => 'local_1,remote_1', 's_ocr' => 'ocrd_1,ocra_1', 's_ocri' => '', 's_dgr' => '', 's_cbtr' => 'scbtrd_1,scbtra_1', 's_ar' => '', 's_aru' => '', 's_tc' => '', 'c_cb' => 'cbctrl_op_1,cbctrl_cl_1', 'c_aru' => '', 'c_rst' => 'rrctrl_on_1', 'c_tc' => '', 'ir_rtu' => '', 'is_rtu' => '', 'it_rtu' => '', 'ir_ms' => '', 'is_ms' => '', 'it_ms' => '', 'ir_scale' => '', 'is_scale' => '', 'it_scale' => '', 'fir_rtu' => '799', 'fis_rtu' => '', 'fit_rtu' => '800', 'fin_rtu' => '8', 'fir_ms' => '799', 'fis_ms' => '', 'fit_ms' => '800', 'fin_ms' => '9', 'fir_scale' => '1', 'fis_scale' => '1\'', 'fit_scale' => '', 'fin_scale' => '1', 'p_rtu' => '', 'p_ms' => '', 'p_scale' => '', 'v_rtu' => '', 'v_ms' => '', 'v_scale' => '', 'f_rtu' => '', 'f_ms' => '', 'f_scale' => '', 'id_komkp' => 2, 'nama_user' => '', 'id_pelms' => '2', 'pelrtu' => 'SELAMET & TEDDY', 'ketpeny' => 'ARUS GANGGUAN DGR DIBUAT MUNCUL PER FASA DI HMI', 'lastupdate' => '2020-08-11 08:16:14.631521'],
            ['id_peny' => 66, 'tgl_kom' => '2020-08-11', 'nama_peny' => 'KEPUTIH', 'id_gi' => 36, 'id_rtugi' => 4, 'rtu_addrs' => 'DNP', 'id_medkom' => 3, 's_cb' => 'open_1,close_1', 's_lr' => 'local_1,remote_1', 's_ocr' => 'ocrd_1,ocra_1', 's_ocri' => '', 's_dgr' => '', 's_cbtr' => 'scbtrd_1,scbtra_1', 's_ar' => '', 's_aru' => '', 's_tc' => '', 'c_cb' => 'cbctrl_op_1,cbctrl_cl_1', 'c_aru' => '', 'c_rst' => 'rrctrl_on_1', 'c_tc' => '', 'ir_rtu' => '', 'is_rtu' => '', 'it_rtu' => '', 'ir_ms' => '', 'is_ms' => '', 'it_ms' => '', 'ir_scale' => '', 'is_scale' => '', 'it_scale' => '', 'fir_rtu' => '800', 'fis_rtu' => '', 'fit_rtu' => '', 'fin_rtu' => '', 'fir_ms' => '800', 'fis_ms' => '', 'fit_ms' => '', 'fin_ms' => '', 'fir_scale' => '1', 'fis_scale' => '\'', 'fit_scale' => '', 'fin_scale' => '', 'p_rtu' => '', 'p_ms' => '', 'p_scale' => '', 'v_rtu' => '', 'v_ms' => '', 'v_scale' => '', 'f_rtu' => '', 'f_ms' => '', 'f_scale' => '', 'id_komkp' => 2, 'nama_user' => '', 'id_pelms' => '2', 'pelrtu' => 'SELAMET & TEDDY', 'ketpeny' => '', 'lastupdate' => '2020-08-11 07:55:15.000000'],
            ['id_peny' => 67, 'tgl_kom' => '2020-08-13', 'nama_peny' => 'INTAKO', 'id_gi' => 29, 'id_rtugi' => 5, 'rtu_addrs' => 'DNP', 'id_medkom' => 3, 's_cb' => 'open_1,close_1', 's_lr' => 'local_1,remote_1', 's_ocr' => 'ocrd_1,ocra_1', 's_ocri' => '', 's_dgr' => 'dgrd_1,dgra_1', 's_cbtr' => '', 's_ar' => '', 's_aru' => '', 's_tc' => '', 'c_cb' => 'cbctrl_op_1,cbctrl_cl_1', 'c_aru' => '', 'c_rst' => '', 'c_tc' => '', 'ir_rtu' => '', 'is_rtu' => '', 'it_rtu' => '', 'ir_ms' => '', 'is_ms' => '', 'it_ms' => '', 'ir_scale' => '', 'is_scale' => '', 'it_scale' => '', 'fir_rtu' => '800', 'fis_rtu' => '', 'fit_rtu' => '800', 'fin_rtu' => '9', 'fir_ms' => '798', 'fis_ms' => '', 'fit_ms' => '798', 'fin_ms' => '9', 'fir_scale' => '0.5', 'fis_scale' => '', 'fit_scale' => '0.5', 'fin_scale' => '0.01', 'p_rtu' => '', 'p_ms' => '', 'p_scale' => '', 'v_rtu' => '', 'v_ms' => '', 'v_scale' => '', 'f_rtu' => '', 'f_ms' => '', 'f_scale' => '', 'id_komkp' => 2, 'nama_user' => '', 'id_pelms' => '2', 'pelrtu' => 'SELAMET & AMI', 'ketpeny' => '', 'lastupdate' => '2020-08-13 04:39:36.000000'],
            ['id_peny' => 68, 'tgl_kom' => '2020-08-13', 'nama_peny' => 'SUGIHWARAS', 'id_gi' => 29, 'id_rtugi' => 5, 'rtu_addrs' => 'DNP', 'id_medkom' => 3, 's_cb' => 'open_1,close_1', 's_lr' => 'local_1,remote_1', 's_ocr' => 'ocrd_1,ocra_1', 's_ocri' => '', 's_dgr' => 'dgrd_1,dgra_1', 's_cbtr' => '', 's_ar' => '', 's_aru' => '', 's_tc' => '', 'c_cb' => 'cbctrl_op_1,cbctrl_cl_1', 'c_aru' => '', 'c_rst' => '', 'c_tc' => '', 'ir_rtu' => '', 'is_rtu' => '', 'it_rtu' => '', 'ir_ms' => '', 'is_ms' => '', 'it_ms' => '', 'ir_scale' => '', 'is_scale' => '', 'it_scale' => '', 'fir_rtu' => '800', 'fis_rtu' => '', 'fit_rtu' => '800', 'fin_rtu' => '9', 'fir_ms' => '799', 'fis_ms' => '', 'fit_ms' => '799', 'fin_ms' => '9', 'fir_scale' => '0.5', 'fis_scale' => '\'', 'fit_scale' => '0.5', 'fin_scale' => '0.01', 'p_rtu' => '', 'p_ms' => '', 'p_scale' => '', 'v_rtu' => '', 'v_ms' => '', 'v_scale' => '', 'f_rtu' => '', 'f_ms' => '', 'f_scale' => '', 'id_komkp' => 2, 'nama_user' => '', 'id_pelms' => '2', 'pelrtu' => 'SELAMET & AMI', 'ketpeny' => '', 'lastupdate' => '2020-08-13 04:40:52.000000'],
            ['id_peny' => 69, 'tgl_kom' => '2020-08-19', 'nama_peny' => 'SUPRIYADI', 'id_gi' => 81, 'id_rtugi' => 5, 'rtu_addrs' => '', 'id_medkom' => 3, 's_cb' => 'open_1,open_3,open_4,close_1,close_3,close_4', 's_lr' => 'local_1,local_3,local_4,remote_1,remote_3,remote_4', 's_ocr' => 'ocrd_1,ocrd_3,ocrd_4,ocra_1,ocra_3,ocra_4', 's_ocri' => '', 's_dgr' => 'dgrd_1,dgrd_3,dgrd_4,dgra_1,dgra_3,dgra_4', 's_cbtr' => 'scbtrd_1,scbtrd_3,scbtrd_4,scbtra_1,scbtra_3,scbtra_4', 's_ar' => '', 's_aru' => '', 's_tc' => '', 'c_cb' => '', 'c_aru' => '', 'c_rst' => 'rrctrl_on_1', 'c_tc' => '', 'ir_rtu' => '', 'is_rtu' => '', 'it_rtu' => '', 'ir_ms' => '', 'is_ms' => '', 'it_ms' => '', 'ir_scale' => '', 'is_scale' => '', 'it_scale' => '', 'fir_rtu' => '595', 'fis_rtu' => '', 'fit_rtu' => '', 'fin_rtu' => '8', 'fir_ms' => '600', 'fis_ms' => '', 'fit_ms' => '', 'fin_ms' => '8', 'fir_scale' => '0.5', 'fis_scale' => '', 'fit_scale' => '', 'fin_scale' => '0.006', 'p_rtu' => '', 'p_ms' => '', 'p_scale' => '', 'v_rtu' => '', 'v_ms' => '', 'v_scale' => '', 'f_rtu' => '', 'f_ms' => '', 'f_scale' => '', 'id_komkp' => 2, 'nama_user' => '', 'id_pelms' => '4', 'pelrtu' => 'Faisal & Lora', 'ketpeny' => '', 'lastupdate' => '2020-08-19 07:32:17.000000'],
            ['id_peny' => 70, 'tgl_kom' => '2020-08-19', 'nama_peny' => 'SUMBER GEMPOL', 'id_gi' => 81, 'id_rtugi' => 5, 'rtu_addrs' => '', 'id_medkom' => 3, 's_cb' => 'open_1,open_3,open_4,close_1,close_3,close_4', 's_lr' => 'local_1,local_3,local_4,remote_1,remote_3,remote_4', 's_ocr' => 'ocrd_1,ocrd_3,ocrd_4,ocra_1,ocra_3,ocra_4', 's_ocri' => 'ocrid_1,ocrid_3,ocrid_4,ocria_1,ocria_3,ocria_4', 's_dgr' => '', 's_cbtr' => 'scbtrd_1,scbtrd_3,scbtrd_4,scbtra_1,scbtra_3,scbtra_4', 's_ar' => '', 's_aru' => '', 's_tc' => '', 'c_cb' => 'cbctrl_op_1,cbctrl_op_3,cbctrl_op_4,cbctrl_cl_1,cbctrl_cl_3,cbctrl_cl_4', 'c_aru' => '', 'c_rst' => 'rrctrl_on_1,rrctrl_on_3,rrctrl_on_4', 'c_tc' => '', 'ir_rtu' => '', 'is_rtu' => '', 'it_rtu' => '', 'ir_ms' => '', 'is_ms' => '', 'it_ms' => '', 'ir_scale' => '', 'is_scale' => '', 'it_scale' => '', 'fir_rtu' => '330', 'fis_rtu' => '', 'fit_rtu' => '', 'fin_rtu' => '12', 'fir_ms' => '330', 'fis_ms' => '', 'fit_ms' => '', 'fin_ms' => '12', 'fir_scale' => '0.5', 'fis_scale' => '', 'fit_scale' => '', 'fin_scale' => '0.006', 'p_rtu' => '', 'p_ms' => '', 'p_scale' => '', 'v_rtu' => '', 'v_ms' => '', 'v_scale' => '', 'f_rtu' => '', 'f_ms' => '', 'f_scale' => '', 'id_komkp' => 2, 'nama_user' => '', 'id_pelms' => '4', 'pelrtu' => 'Faisal & Lora', 'ketpeny' => '', 'lastupdate' => '2020-08-19 08:28:45.000000'],
            ['id_peny' => 71, 'tgl_kom' => '2020-08-19', 'nama_peny' => 'NGANTRU', 'id_gi' => 81, 'id_rtugi' => 5, 'rtu_addrs' => '', 'id_medkom' => 3, 's_cb' => 'open_1,open_3,open_4,close_1,close_3,close_4', 's_lr' => 'local_1,local_3,local_4,remote_1,remote_3,remote_4', 's_ocr' => 'ocrd_1,ocrd_3,ocrd_4,ocra_1,ocra_3,ocra_4', 's_ocri' => '', 's_dgr' => '', 's_cbtr' => '', 's_ar' => '', 's_aru' => '', 's_tc' => '', 'c_cb' => 'cbctrl_op_1,cbctrl_op_3,cbctrl_op_4,cbctrl_cl_1,cbctrl_cl_3,cbctrl_cl_4', 'c_aru' => '', 'c_rst' => '', 'c_tc' => '', 'ir_rtu' => '', 'is_rtu' => '', 'it_rtu' => '', 'ir_ms' => '', 'is_ms' => '', 'it_ms' => '', 'ir_scale' => '', 'is_scale' => '', 'it_scale' => '', 'fir_rtu' => '599', 'fis_rtu' => '', 'fit_rtu' => '', 'fin_rtu' => '', 'fir_ms' => '600', 'fis_ms' => '', 'fit_ms' => '', 'fin_ms' => '', 'fir_scale' => '0.5', 'fis_scale' => '', 'fit_scale' => '', 'fin_scale' => '', 'p_rtu' => '', 'p_ms' => '', 'p_scale' => '', 'v_rtu' => '', 'v_ms' => '', 'v_scale' => '', 'f_rtu' => '', 'f_ms' => '', 'f_scale' => '', 'id_komkp' => 2, 'nama_user' => '', 'id_pelms' => '4', 'pelrtu' => 'Faisal & Lora', 'ketpeny' => '', 'lastupdate' => '2020-08-19 08:28:51.000000'],
            ['id_peny' => 73, 'tgl_kom' => '2020-08-19', 'nama_peny' => 'OLEHAN', 'id_gi' => 108, 'id_rtugi' => 5, 'rtu_addrs' => 'DNP', 'id_medkom' => 3, 's_cb' => 'open_1,close_1', 's_lr' => 'local_1,remote_1', 's_ocr' => 'ocrd_1,ocra_1', 's_ocri' => 'ocrid_1,ocria_1', 's_dgr' => 'dgrd_1,dgra_1', 's_cbtr' => 'scbtrd_1,scbtra_1', 's_ar' => '', 's_aru' => '', 's_tc' => '', 'c_cb' => 'cbctrl_op_1,cbctrl_cl_1', 'c_aru' => '', 'c_rst' => 'rrctrl_on_1', 'c_tc' => '', 'ir_rtu' => '', 'is_rtu' => '', 'it_rtu' => '', 'ir_ms' => '', 'is_ms' => '', 'it_ms' => '', 'ir_scale' => '', 'is_scale' => '', 'it_scale' => '', 'fir_rtu' => '2,3', 'fis_rtu' => '', 'fit_rtu' => '', 'fin_rtu' => '', 'fir_ms' => '2,323', 'fis_ms' => '', 'fit_ms' => '', 'fin_ms' => '', 'fir_scale' => '0.5', 'fis_scale' => '0.5', 'fit_scale' => '', 'fin_scale' => '', 'p_rtu' => '', 'p_ms' => '', 'p_scale' => '', 'v_rtu' => '', 'v_ms' => '', 'v_scale' => '', 'f_rtu' => '', 'f_ms' => '', 'f_scale' => '', 'id_komkp' => 2, 'nama_user' => '', 'id_pelms' => '2', 'pelrtu' => 'RAHMAT', 'ketpeny' => 'HASIL UJI ARUS GANGGUAN :\r\nOCR : 599\r\nOCRI : 2273\r', 'lastupdate' => '2020-08-19 07:34:02.000000'],
            ['id_peny' => 74, 'tgl_kom' => '2020-08-19', 'nama_peny' => 'RAMBAN', 'id_gi' => 108, 'id_rtugi' => 5, 'rtu_addrs' => 'DNP', 'id_medkom' => 3, 's_cb' => 'open_1,close_2', 's_lr' => 'local_1,remote_1', 's_ocr' => 'ocrd_1,ocra_1', 's_ocri' => 'ocrid_1,ocria_1', 's_dgr' => 'dgrd_1,dgra_1', 's_cbtr' => 'scbtrd_1,scbtra_1', 's_ar' => '', 's_aru' => '', 's_tc' => '', 'c_cb' => 'cbctrl_op_1,cbctrl_cl_1', 'c_aru' => '', 'c_rst' => 'rrctrl_on_1', 'c_tc' => '', 'ir_rtu' => '', 'is_rtu' => '', 'it_rtu' => '', 'ir_ms' => '', 'is_ms' => '', 'it_ms' => '', 'ir_scale' => '', 'is_scale' => '', 'it_scale' => '', 'fir_rtu' => '', 'fis_rtu' => '', 'fit_rtu' => '', 'fin_rtu' => '', 'fir_ms' => '', 'fis_ms' => '', 'fit_ms' => '', 'fin_ms' => '', 'fir_scale' => '', 'fis_scale' => '', 'fit_scale' => '', 'fin_scale' => '', 'p_rtu' => '', 'p_ms' => '', 'p_scale' => '', 'v_rtu' => '', 'v_ms' => '', 'v_scale' => '', 'f_rtu' => '', 'f_ms' => '', 'f_scale' => '', 'id_komkp' => 2, 'nama_user' => '', 'id_pelms' => '2', 'pelrtu' => 'RAHMAT', 'ketpeny' => 'HASIL UJI :\r\nOCR : 599\r\nOCRI : 2202\r\nDGR : 8\r\n\r\nNO', 'lastupdate' => '2020-08-19 07:35:35.000000'],
            ['id_peny' => 75, 'tgl_kom' => '2020-08-19', 'nama_peny' => 'KALI DAWIR', 'id_gi' => 81, 'id_rtugi' => 5, 'rtu_addrs' => '', 'id_medkom' => 3, 's_cb' => 'open_1,open_3,open_4,close_1,close_3,close_4', 's_lr' => 'local_1,local_3,local_4,remote_1,remote_3,remote_4', 's_ocr' => 'ocrd_1,ocrd_3,ocrd_4,ocra_1,ocra_3,ocra_4', 's_ocri' => 'ocrid_1,ocrid_3,ocrid_4,ocria_1,ocria_3,ocria_4', 's_dgr' => 'dgrd_1,dgrd_3,dgrd_4,dgra_1,dgra_3,dgra_4', 's_cbtr' => 'scbtrd_1,scbtrd_3,scbtrd_4,scbtra_1,scbtra_3,scbtra_4', 's_ar' => '', 's_aru' => '', 's_tc' => '', 'c_cb' => 'cbctrl_op_1,cbctrl_op_3,cbctrl_op_4,cbctrl_cl_1,cbctrl_cl_3,cbctrl_cl_4', 'c_aru' => '', 'c_rst' => 'rrctrl_on_1,rrctrl_on_3,rrctrl_on_4', 'c_tc' => '', 'ir_rtu' => '', 'is_rtu' => '', 'it_rtu' => '', 'ir_ms' => '', 'is_ms' => '', 'it_ms' => '', 'ir_scale' => '', 'is_scale' => '', 'it_scale' => '', 'fir_rtu' => '600', 'fis_rtu' => '', 'fit_rtu' => '', 'fin_rtu' => '8', 'fir_ms' => '600', 'fis_ms' => '', 'fit_ms' => '', 'fin_ms' => '8', 'fir_scale' => '0.5', 'fis_scale' => '', 'fit_scale' => '', 'fin_scale' => '0.006', 'p_rtu' => '', 'p_ms' => '', 'p_scale' => '', 'v_rtu' => '', 'v_ms' => '', 'v_scale' => '', 'f_rtu' => '', 'f_ms' => '', 'f_scale' => '', 'id_komkp' => 2, 'nama_user' => '', 'id_pelms' => '4', 'pelrtu' => 'Faisal & Lora', 'ketpeny' => '', 'lastupdate' => '2020-08-19 07:31:53.000000'],
            ['id_peny' => 76, 'tgl_kom' => '2020-08-19', 'nama_peny' => 'WONOREJO 1', 'id_gi' => 81, 'id_rtugi' => 5, 'rtu_addrs' => '', 'id_medkom' => 3, 's_cb' => 'open_1,open_3,open_4,close_1,close_3,close_4', 's_lr' => 'local_1,local_3,local_4,remote_1,remote_3,remote_4', 's_ocr' => 'ocrd_1,ocrd_3,ocrd_4,ocra_1,ocra_3,ocra_4', 's_ocri' => '', 's_dgr' => '', 's_cbtr' => '', 's_ar' => '', 's_aru' => '', 's_tc' => '', 'c_cb' => 'cbctrl_op_1,cbctrl_op_3,cbctrl_op_4,cbctrl_cl_1,cbctrl_cl_3,cbctrl_cl_4', 'c_aru' => '', 'c_rst' => 'rrctrl_on_1,rrctrl_on_3,rrctrl_on_4', 'c_tc' => '', 'ir_rtu' => '', 'is_rtu' => '', 'it_rtu' => '', 'ir_ms' => '', 'is_ms' => '', 'it_ms' => '', 'ir_scale' => '', 'is_scale' => '', 'it_scale' => '', 'fir_rtu' => '600', 'fis_rtu' => '', 'fit_rtu' => '', 'fin_rtu' => '8', 'fir_ms' => '600', 'fis_ms' => '600', 'fit_ms' => '600', 'fin_ms' => '600', 'fir_scale' => '0.5', 'fis_scale' => '0.5', 'fit_scale' => '', 'fin_scale' => '0.006', 'p_rtu' => '', 'p_ms' => '', 'p_scale' => '', 'v_rtu' => '', 'v_ms' => '', 'v_scale' => '', 'f_rtu' => '', 'f_ms' => '', 'f_scale' => '', 'id_komkp' => 2, 'nama_user' => '', 'id_pelms' => '4', 'pelrtu' => 'Faisal & Lora', 'ketpeny' => '', 'lastupdate' => '2020-08-19 07:29:44.000000'],
            ['id_peny' => 77, 'tgl_kom' => '2020-08-19', 'nama_peny' => 'TAL KANDANG', 'id_gi' => 108, 'id_rtugi' => 5, 'rtu_addrs' => 'DNP', 'id_medkom' => 3, 's_cb' => 'open_1,close_1', 's_lr' => 'local_1,remote_1', 's_ocr' => 'ocrd_1,ocra_1', 's_ocri' => 'ocrid_1,ocria_1', 's_dgr' => 'dgrd_1,dgra_1', 's_cbtr' => 'scbtrd_1,scbtra_1', 's_ar' => '', 's_aru' => '', 's_tc' => '', 'c_cb' => 'cbctrl_op_1,cbctrl_cl_1', 'c_aru' => '', 'c_rst' => 'rrctrl_on_1', 'c_tc' => '', 'ir_rtu' => '', 'is_rtu' => '', 'it_rtu' => '', 'ir_ms' => '', 'is_ms' => '', 'it_ms' => '', 'ir_scale' => '', 'is_scale' => '', 'it_scale' => '', 'fir_rtu' => '', 'fis_rtu' => '', 'fit_rtu' => '', 'fin_rtu' => '', 'fir_ms' => '', 'fis_ms' => '', 'fit_ms' => '', 'fin_ms' => '', 'fir_scale' => '', 'fis_scale' => '\'', 'fit_scale' => '', 'fin_scale' => '', 'p_rtu' => '', 'p_ms' => '', 'p_scale' => '', 'v_rtu' => '', 'v_ms' => '', 'v_scale' => '', 'f_rtu' => '', 'f_ms' => '', 'f_scale' => '', 'id_komkp' => 2, 'nama_user' => '', 'id_pelms' => '2', 'pelrtu' => 'RAHMAT', 'ketpeny' => 'HASIL UJI ARUS GANGGUAN\r\nOCR : 601\r\nOCRI : 2342\r\nD', 'lastupdate' => '2020-08-19 07:05:11.000000'],
            ['id_peny' => 78, 'tgl_kom' => '2020-08-19', 'nama_peny' => 'ASEM BAGUS', 'id_gi' => 108, 'id_rtugi' => 5, 'rtu_addrs' => '', 'id_medkom' => 3, 's_cb' => 'open_1,close_1', 's_lr' => 'local_1,remote_1', 's_ocr' => 'ocrd_1,ocra_1', 's_ocri' => 'ocrid_1,ocria_1', 's_dgr' => 'dgrd_1,dgra_1', 's_cbtr' => 'scbtrd_1,scbtra_1', 's_ar' => '', 's_aru' => '', 's_tc' => '', 'c_cb' => 'cbctrl_op_1,cbctrl_cl_1', 'c_aru' => '', 'c_rst' => 'rrctrl_off_2,rrctrl_on_2', 'c_tc' => '', 'ir_rtu' => '', 'is_rtu' => '', 'it_rtu' => '', 'ir_ms' => '', 'is_ms' => '', 'it_ms' => '', 'ir_scale' => '', 'is_scale' => '', 'it_scale' => '', 'fir_rtu' => '600', 'fis_rtu' => '600', 'fit_rtu' => '600', 'fin_rtu' => '11', 'fir_ms' => '600', 'fis_ms' => '600', 'fit_ms' => '600', 'fin_ms' => '11', 'fir_scale' => '0.5', 'fis_scale' => '0.5\'0.006', 'fit_scale' => '', 'fin_scale' => '0.006', 'p_rtu' => '', 'p_ms' => '', 'p_scale' => '', 'v_rtu' => '', 'v_ms' => '', 'v_scale' => '', 'f_rtu' => '', 'f_ms' => '', 'f_scale' => '', 'id_komkp' => 2, 'nama_user' => '', 'id_pelms' => '3', 'pelrtu' => 'Rachmad - Dymas', 'ketpeny' => 'Control reset tidak bisa dari master & RTU', 'lastupdate' => '2020-08-19 08:33:47.000000'],
            ['id_peny' => 79, 'tgl_kom' => '2020-08-19', 'nama_peny' => 'Ramban', 'id_gi' => 108, 'id_rtugi' => 5, 'rtu_addrs' => '', 'id_medkom' => 3, 's_cb' => 'open_1,close_1', 's_lr' => '', 's_ocr' => '', 's_ocri' => '', 's_dgr' => '', 's_cbtr' => '', 's_ar' => '', 's_aru' => '', 's_tc' => '', 'c_cb' => 'cbctrl_op_1,cbctrl_cl_1', 'c_aru' => '', 'c_rst' => '', 'c_tc' => '', 'ir_rtu' => '', 'is_rtu' => '', 'it_rtu' => '', 'ir_ms' => '', 'is_ms' => '', 'it_ms' => '', 'ir_scale' => '', 'is_scale' => '', 'it_scale' => '', 'fir_rtu' => '', 'fis_rtu' => '', 'fit_rtu' => '', 'fin_rtu' => '', 'fir_ms' => '', 'fis_ms' => '', 'fit_ms' => '', 'fin_ms' => '', 'fir_scale' => '', 'fis_scale' => '\'', 'fit_scale' => '', 'fin_scale' => '', 'p_rtu' => '', 'p_ms' => '', 'p_scale' => '', 'v_rtu' => '', 'v_ms' => '', 'v_scale' => '', 'f_rtu' => '', 'f_ms' => '', 'f_scale' => '', 'id_komkp' => 1, 'nama_user' => '', 'id_pelms' => '3', 'pelrtu' => 'Rachmad - Dymas', 'ketpeny' => '', 'lastupdate' => '2020-09-14 06:26:31.000000'],
            ['id_peny' => 80, 'tgl_kom' => '2020-08-19', 'nama_peny' => 'Tal Kandang', 'id_gi' => 108, 'id_rtugi' => 5, 'rtu_addrs' => '', 'id_medkom' => 3, 's_cb' => 'open_1,close_1', 's_lr' => '', 's_ocr' => '', 's_ocri' => '', 's_dgr' => '', 's_cbtr' => '', 's_ar' => '', 's_aru' => '', 's_tc' => '', 'c_cb' => 'cbctrl_op_1,cbctrl_cl_1', 'c_aru' => '', 'c_rst' => '', 'c_tc' => '', 'ir_rtu' => '', 'is_rtu' => '', 'it_rtu' => '', 'ir_ms' => '', 'is_ms' => '', 'it_ms' => '', 'ir_scale' => '', 'is_scale' => '', 'it_scale' => '', 'fir_rtu' => '', 'fis_rtu' => '', 'fit_rtu' => '', 'fin_rtu' => '', 'fir_ms' => '', 'fis_ms' => '', 'fit_ms' => '', 'fin_ms' => '', 'fir_scale' => '', 'fis_scale' => '\'', 'fit_scale' => '', 'fin_scale' => '', 'p_rtu' => '', 'p_ms' => '', 'p_scale' => '', 'v_rtu' => '', 'v_ms' => '', 'v_scale' => '', 'f_rtu' => '', 'f_ms' => '', 'f_scale' => '', 'id_komkp' => 2, 'nama_user' => '', 'id_pelms' => '3', 'pelrtu' => 'Rachmad - Dymas', 'ketpeny' => '', 'lastupdate' => '2020-09-14 06:26:06.000000'],
            ['id_peny' => 81, 'tgl_kom' => '2020-08-22', 'nama_peny' => 'KALIKUNTING', 'id_gi' => 83, 'id_rtugi' => 5, 'rtu_addrs' => '', 'id_medkom' => 3, 's_cb' => '', 's_lr' => 'local_1,local_3,local_4,remote_1,remote_3,remote_4', 's_ocr' => 'ocrd_1,ocrd_3,ocrd_4,ocra_1,ocra_3,ocra_4', 's_ocri' => 'ocrid_1,ocrid_3,ocrid_4,ocria_1,ocria_3,ocria_4', 's_dgr' => 'dgrd_1,dgrd_3,dgrd_4,dgra_1,dgra_3,dgra_4', 's_cbtr' => 'scbtrd_1,scbtrd_3,scbtrd_4,scbtra_1,scbtra_3,scbtra_4', 's_ar' => '', 's_aru' => '', 's_tc' => '', 'c_cb' => 'cbctrl_op_1,cbctrl_cl_1', 'c_aru' => '', 'c_rst' => '', 'c_tc' => '', 'ir_rtu' => '', 'is_rtu' => '', 'it_rtu' => '', 'ir_ms' => '', 'is_ms' => '', 'it_ms' => '', 'ir_scale' => '', 'is_scale' => '', 'it_scale' => '', 'fir_rtu' => '439', 'fis_rtu' => '', 'fit_rtu' => '', 'fin_rtu' => '20', 'fir_ms' => '439', 'fis_ms' => '', 'fit_ms' => '', 'fin_ms' => '20', 'fir_scale' => '1', 'fis_scale' => '', 'fit_scale' => '', 'fin_scale' => '0.003', 'p_rtu' => '', 'p_ms' => '', 'p_scale' => '', 'v_rtu' => '', 'v_ms' => '', 'v_scale' => '', 'f_rtu' => '', 'f_ms' => '', 'f_scale' => '', 'id_komkp' => 2, 'nama_user' => '', 'id_pelms' => '4', 'pelrtu' => 'Agung/Rahmad', 'ketpeny' => '- Status CB tidak berubah, menunggu penormalan\r\n- Reset belum termaping di RTU', 'lastupdate' => '2020-08-26 06:59:29.000000'],
            ['id_peny' => 82, 'tgl_kom' => '2020-08-22', 'nama_peny' => 'KENEP', 'id_gi' => 83, 'id_rtugi' => 5, 'rtu_addrs' => '', 'id_medkom' => 3, 's_cb' => 'open_1,open_3,open_4,close_1,close_3,close_4', 's_lr' => 'local_1,local_3,local_4,remote_1,remote_3,remote_4', 's_ocr' => 'ocrd_1,ocrd_3,ocrd_4,ocra_1,ocra_3,ocra_4', 's_ocri' => 'ocrid_1,ocrid_3,ocrid_4,ocria_1,ocria_3,ocria_4', 's_dgr' => 'dgrd_1,dgrd_3,dgrd_4,dgra_1,dgra_3,dgra_4', 's_cbtr' => 'scbtrd_1,scbtrd_3,scbtrd_4,scbtra_1,scbtra_3,scbtra_4', 's_ar' => '', 's_aru' => '', 's_tc' => '', 'c_cb' => 'cbctrl_op_1,cbctrl_op_3,cbctrl_op_4,cbctrl_cl_1,cbctrl_cl_3,cbctrl_cl_4', 'c_aru' => '', 'c_rst' => '', 'c_tc' => '', 'ir_rtu' => '', 'is_rtu' => '', 'it_rtu' => '', 'ir_ms' => '', 'is_ms' => '', 'it_ms' => '', 'ir_scale' => '', 'is_scale' => '', 'it_scale' => '', 'fir_rtu' => '773', 'fis_rtu' => '', 'fit_rtu' => '', 'fin_rtu' => '20', 'fir_ms' => '773', 'fis_ms' => '', 'fit_ms' => '', 'fin_ms' => '20', 'fir_scale' => '1', 'fis_scale' => '', 'fit_scale' => '', 'fin_scale' => '0.003', 'p_rtu' => '', 'p_ms' => '', 'p_scale' => '', 'v_rtu' => '', 'v_ms' => '', 'v_scale' => '', 'f_rtu' => '', 'f_ms' => '', 'f_scale' => '', 'id_komkp' => 2, 'nama_user' => '', 'id_pelms' => '4', 'pelrtu' => 'Agung/Rahmad', 'ketpeny' => '- Status CB tidak berubah, menunggu penormalan\r\n- Reset belum termaping di RTU', 'lastupdate' => '2020-08-24 01:32:07.000000'],
            ['id_peny' => 83, 'tgl_kom' => '2020-08-22', 'nama_peny' => 'ORO ORO OMBO', 'id_gi' => 83, 'id_rtugi' => 5, 'rtu_addrs' => '', 'id_medkom' => 3, 's_cb' => '', 's_lr' => 'local_1,local_3,local_4,remote_1,remote_3,remote_4', 's_ocr' => 'ocrd_1,ocrd_3,ocrd_4,ocra_1,ocra_3,ocra_4', 's_ocri' => 'ocrid_1,ocrid_3,ocrid_4,ocria_1,ocria_3,ocria_4', 's_dgr' => 'dgrd_1,dgrd_3,dgrd_4,dgra_1,dgra_3,dgra_4', 's_cbtr' => 'scbtrd_1,scbtrd_3,scbtrd_4,scbtra_1,scbtra_3,scbtra_4', 's_ar' => '', 's_aru' => '', 's_tc' => '', 'c_cb' => '', 'c_aru' => '', 'c_rst' => '', 'c_tc' => '', 'ir_rtu' => '', 'is_rtu' => '', 'it_rtu' => '', 'ir_ms' => '', 'is_ms' => '', 'it_ms' => '', 'ir_scale' => '', 'is_scale' => '', 'it_scale' => '', 'fir_rtu' => '7135', 'fis_rtu' => '', 'fit_rtu' => '', 'fin_rtu' => '20', 'fir_ms' => '7135', 'fis_ms' => '', 'fit_ms' => '', 'fin_ms' => '20', 'fir_scale' => '1', 'fis_scale' => '', 'fit_scale' => '', 'fin_scale' => '0.003', 'p_rtu' => '', 'p_ms' => '', 'p_scale' => '', 'v_rtu' => '', 'v_ms' => '', 'v_scale' => '', 'f_rtu' => '', 'f_ms' => '', 'f_scale' => '', 'id_komkp' => 2, 'nama_user' => '', 'id_pelms' => '4', 'pelrtu' => 'Agung/Rahmad', 'ketpeny' => '- Status CB tidak berubah, menunggu penormalan\r\n- Control CB mengalami anomali saat control, menunggu penormalan\r\n- Reset belum termaping di RTU', 'lastupdate' => '2020-08-24 01:34:25.000000'],
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        DB::table('tb_formpeny')->truncate();
        Schema::dropIfExists('tb_formpeny');
    }
};
