<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Keypoint extends Model
{
    protected $table = 'tb_formkp';
    protected $primaryKey = 'id_formkp';

    // Disable timestamps
    public $timestamps = false;

    protected $fillable = [
        'tgl_komisioning',
        'nama_lbs',
        'id_merkrtu',
        'id_modem',
        'rtu_addrs',
        'id_medkom',
        'ip_kp',
        'id_gi',
        'nama_peny',
        'id_sec',

        // --- ARUS BEBAN (Existing) ---
        'ir_rtu',
        'ir_ms',
        'ir_scale',
        'is_rtu',
        'is_ms',
        'is_scale',
        'it_rtu',
        'it_ms',
        'it_scale',

        // --- TEGANGAN INPUT (Updated vr -> vrin) ---
        'vrin_rtu',
        'vrin_ms',
        'vrin_scale',
        'vsin_rtu',
        'vsin_ms',
        'vsin_scale',
        'vtin_rtu',
        'vtin_ms',
        'vtin_scale',

        // --- TEGANGAN OUTPUT (New) ---
        'vrout_rtu',
        'vrout_ms',
        'vrout_scale',
        'vsout_rtu',
        'vsout_ms',
        'vsout_scale',
        'vtout_rtu',
        'vtout_ms',
        'vtout_scale',

        // --- FREKUENSI, ARUS RATA2, PF (New) ---
        'hz_rtu',
        'hz_ms',
        'hz_scale',
        'iavg_rtu',
        'iavg_ms',
        'iavg_scale',
        'pf_rtu',
        'pf_ms',
        'pf_scale',

        // --- ARUS GANGGUAN / FAULT (New) ---
        'ifr_rtu',
        'ifr_ms',
        'ifr_scale',
        'ifs_rtu',
        'ifs_ms',
        'ifs_scale',
        'ift_rtu',
        'ift_ms',
        'ift_scale',
        'ifn_rtu',
        'ifn_ms',
        'ifn_scale',

        // --- ARUS GANGGUAN PSEUDO (New) ---
        'ifr_psuedo_rtu',
        'ifr_psuedo_ms',
        'ifr_psuedo_scale',
        'ifs_psuedo_rtu',
        'ifs_psuedo_ms',
        'ifs_psuedo_scale',
        'ift_psuedo_rtu',
        'ift_psuedo_ms',
        'ift_psuedo_scale',
        'ifn_psuedo_rtu',
        'ifn_psuedo_ms',
        'ifn_psuedo_scale',

        // --- Data Lainnya ---
        'id_komkp',
        'nama_user',
        'id_pelms',
        'id_pelrtu',
        'catatankp',

        // --- Checkbox Groups ---
        's_cb',
        's_cb2',
        's_lr',
        's_door',
        's_acf',
        's_dcf',
        's_dcd',
        's_hlt',
        's_sf6',
        's_fir',
        's_fis',
        's_fit',
        's_fin',
        's_comf',
        's_lruf',
        'c_cb',
        'c_cb2',
        'c_hlt',
        'c_rst',

        // --- Strings for MS/RTU/ObjFrmt ---
        'sacf_fail_addms',
        'sacf_fail_addrtu',
        'sacf_fail_objfrmt',
        'sacf_normal_addms',
        'sacf_normal_addrtu',
        'sacf_normal_objfrmt',
        'scb2_close_addms',
        'scb2_close_addrtu',
        'scb2_close_objfrmt',
        'scb2_open_addms',
        'scb2_open_addrtu',
        'scb2_open_objfrmt',
        'scb_close_addms',
        'scb_close_addrtu',
        'scb_close_objfrmt',
        'scb_open_addms',
        'scb_open_addrtu',
        'scb_open_objfrmt',
        'sdcd_fail_addms',
        'sdcd_fail_addrtu',
        'sdcd_fail_objfrmt',
        'sdcd_normal_addms',
        'sdcd_normal_addrtu',
        'sdcd_normal_objfrmt',
        'sdcf_fail_addms',
        'sdcf_fail_addrtu',
        'sdcf_fail_objfrmt',
        'sdcf_normal_addms',
        'sdcf_normal_addrtu',
        'sdcf_normal_objfrmt',
        'sdoor_close_addms',
        'sdoor_close_addrtu',
        'sdoor_close_objfrmt',
        'sdoor_open_addms',
        'sdoor_open_addrtu',
        'sdoor_open_objfrmt',
        'sfin_fail_addms',
        'sfin_fail_addrtu',
        'sfin_fail_objfrmt',
        'sfin_normal_addms',
        'sfin_normal_addrtu',
        'sfin_normal_objfrmt',
        'sfir_fail_addms',
        'sfir_fail_addrtu',
        'sfir_fail_objfrmt',
        'sfir_normal_addms',
        'sfir_normal_addrtu',
        'sfir_normal_objfrmt',
        'sfis_fail_addms',
        'sfis_fail_addrtu',
        'sfis_fail_objfrmt',
        'sfis_normal_addms',
        'sfis_normal_addrtu',
        'sfis_normal_objfrmt',
        'sfit_fail_addms',
        'sfit_fail_addrtu',
        'sfit_fail_objfrmt',
        'sfit_normal_addms',
        'sfit_normal_addrtu',
        'sfit_normal_objfrmt',
        'shlt_off_addms',
        'shlt_off_addrtu',
        'shlt_off_objfrmt',
        'shlt_on_addms',
        'shlt_on_addrtu',
        'shlt_on_objfrmt',
        'slr_local_addms',
        'slr_local_addrtu',
        'slr_local_objfrmt',
        'slr_remote_addms',
        'slr_remote_addrtu',
        'slr_remote_objfrmt',
        'slruf_addms',
        'slruf_addrtu',
        'slruf_objfrmt',
        'ssf6_fail_addms',
        'ssf6_fail_addrtu',
        'ssf6_fail_objfrmt',
        'ssf6_normal_addms',
        'ssf6_normal_addrtu',
        'ssf6_normal_objfrmt',

        // Control Fields
        'ccb_open_addms',
        'ccb_open_addrtu',
        'ccb_open_objfrmt',
        'ccb_close_addms',
        'ccb_close_addrtu',
        'ccb_close_objfrmt',
        'ccb2_open_addms',
        'ccb2_open_addrtu',
        'ccb2_open_objfrmt',
        'ccb2_close_addms',
        'ccb2_close_addrtu',
        'ccb2_close_objfrmt',
        'chlt_on_addms',
        'chlt_on_addrtu',
        'chlt_on_objfrmt',
        'chlt_off_addms',
        'chlt_off_addrtu',
        'chlt_off_objfrmt',
        'crst_addms',
        'crst_addrtu',
        'crst_objfrmt',

        // Keterangan Fields
        'ketfd',
        'ketfts',
        'ketftc',
        'ketftm',
        'ketpk',

        // SYS Group
        'sys_comf',
        'sys_lruf',
        'sys_signs',
        'sys_limitswith',
        'sys_comf_input',
        'sys_lruf_input',
        'sys_signs_input',
        'sys_limitswith_input',
        'ketsys',

        // HARD Group
        'hard_batere',
        'hard_ps220',
        'hard_charger',
        'hard_limitswith',
        'hard_batere_input',
        'hard_ps220_input',
        'hard_charger_input',
        'hard_limitswith_input',
        'kethard',

        // RE Group
        're_ar_on',
        're_ar_off',
        're_ctrl_ar_on',
        're_ctrl_ar_off',
        'ketre',

        // IN & VAVG Group
        'iavg_rtu',
        'iavg_ms',
        'iavg_scale',
        'in_rtu',
        'in_ms',
        'in_scale',
        'vavg_rtu',
        'vavg_ms',
        'vavg_scale',
// --- Additional Fields for Telemetering ---
        'ir_addrtu',
        'ir_addms',
        'ir_addobjfrmt',
        'is_addrtu',
        'is_addms',
        'is_addobjfrmt',
        'it_addrtu',
        'it_addms',
        'it_addobjfrmt',
        'in_addrtu',
        'in_addms',
        'in_addobjfrmt',
        'vrin_addrtu',
        'vrin_addms',
        'vrin_addobjfrmt',
        'vsin_addrtu',
        'vsin_addms',
        'vsin_addobjfrmt',
        'vtin_addrtu',
        'vtin_addms',
        'vtin_addobjfrmt',
        'vrout_addrtu',
        'vrout_addms',
        'vrout_addobjfrmt',
        'vsout_addrtu',
        'vsout_addms',
        'vsout_addobjfrmt',
        'vtout_addrtu',
        'vtout_addms',
        'vtout_addobjfrmt',
        'vavg_addrtu',
        'vavg_addms',
        'vavg_addobjfrmt',
        'ifr_addrtu',
        'ifr_addms',
        'ifr_addobjfrmt',
        'ifs_addrtu',
        'ifs_addms',
        'ifs_addobjfrmt',
        'ift_addrtu',
        'ift_addms',
        'ift_addobjfrmt',
        'ifn_addrtu',
        'ifn_addms',
        'ifn_addobjfrmt',
        'ifr_psuedo_addrtu',
        'ifr_psuedo_addms',
        'ifr_psuedo_addobjfrmt',
        'ifs_psuedo_addrtu',
        'ifs_psuedo_addms',
        'ifs_psuedo_addobjfrmt',
        'ift_psuedo_addrtu',
        'ift_psuedo_addms',
        'ift_psuedo_addobjfrmt',
        'ifn_psuedo_addrtu',
        'ifn_psuedo_addms',
        'ifn_psuedo_addobjfrmt',
        'hz_addrtu',
        'hz_addms',
        'hz_addobjfrmt',
        'iavg_addrtu',
        'iavg_addms',
        'iavg_addobjfrmt',
        'pf_addrtu',
        'pf_addms',
        'pf_addobjfrmt',
        
    ];
}