<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Penyulangan extends Model
{
    protected $table = 'tb_formpeny';
    protected $primaryKey = 'id_peny';

    public $timestamps = false;

    protected $fillable = [
        'tgl_kom',
        'nama_peny',
        'id_gi',
        'id_rtugi',
        'rtu_addrs',
        'id_medkom',
        's_cb',
        's_lr',
        's_ocr',
        's_ocri',
        's_dgr',
        's_cbtr',
        's_ar',
        's_aru',
        's_tc',
        'c_cb',
        'c_aru',
        'c_rst',
        'c_tc',
        'ir_rtu',
        'is_rtu',
        'it_rtu',
        'ir_ms',
        'is_ms',
        'it_ms',
        'ir_scale',
        'is_scale',
        'it_scale',
        'fir_rtu',
        'fis_rtu',
        'fit_rtu',
        'fin_rtu',
        'fir_ms',
        'fis_ms',
        'fit_ms',
        'fin_ms',
        'fir_scale',
        'fis_scale',
        'fit_scale',
        'fin_scale',
        'v_rtu',
        'v_ms',
        'v_scale',
        'id_komkp',
        'nama_user',
        'id_pelms',
        'id_pelrtu',
        'catatanpeny',
        'lastupdate',
        'scb_open_address',
        'scb_close_address',
        'slocal_address',
        'sremote_address',
        'socr_dis_address',
        'socr_app_address',
        'socri_dis_address',
        'socri_app_address',
        'sdgr_dis_address',
        'sdgr_app_address',
        'scbtr_dis_address',
        'scbtr_app_address',
        'sar_dis_address',
        'sar_app_address',
        'saru_dis_address',
        'saru_app_address',
        'stc_dis_address',
        'stc_app_address',
        'scb_open_objfrmt',
        'scb_close_objfrmt',
        'slocal_objfrmt',
        'sremote_objfrmt',
        'socr_dis_objfrmt',
        'socr_app_objfrmt',
        'socri_dis_objfrmt',
        'socri_app_objfrmt',
        'sdgr_dis_objfrmt',
        'sdgr_app_objfrmt',
        'scbtr_dis_objfrmt',
        'scbtr_app_objfrmt',
        'sar_dis_objfrmt',
        'sar_app_objfrmt',
        'saru_dis_objfrmt',
        'saru_app_objfrmt',
        'stc_dis_objfrmt',
        'stc_app_objfrmt',
        'ccb_open_address',
        'ccb_close_address',
        'caru_use_address',
        'caru_unuse_address',
        'creset_on_address',
        'ctc_raiser_address',
        'ctc_lower_address',
        'ccb_open_objfrmt',
        'ccb_close_objfrmt',
        'caru_use_objfrmt',
        'caru_unuse_objfrmt',
        'creset_on_objfrmt',
        'ctc_raiser_objfrmt',
        'ctc_lower_objfrmt',
        'ketfd',
        'ketfts',
        'ketftc',
        'ketftm',
        'ketfpk',
    ];
}
